### ISSUE TITLE
Google Sign in not working

### ISSUE THREAD

**Issue by laudarch** [laudarch/kbo_qa#1]
When you login with google it goes to a dead endpoint.

**Comment by JeanHuit** [comment]
Makes mention of a redirecet_uri_mismatch.
page navigates to a console.developers.... instead of a  kbo.technology/...
<img width="414" alt="screen shot 2017-07-25 at 8 39 24 pm" src="https://user-images.githubusercontent.com/3165494/28592887-f9f93b3e-7179-11e7-84c0-84e7dfb7e796.png">

**Comment by laudarch** [comment]
Fixed.
