### ISSUE TITLE
Registering a new account

### ISSUE THREAD

**Issue by JeanHuit** [laudarch/kbo_qa#2]
Recaptcha fails.
Even after giving the green check mark   
<img width="665" alt="screen shot 2017-07-25 at 8 34 52 pm" src="https://user-images.githubusercontent.com/3165494/28592977-513e7cba-717a-11e7-9428-49876be20bac.png">
<img width="323" alt="screen shot 2017-07-25 at 8 35 39 pm" src="https://user-images.githubusercontent.com/3165494/28592978-514418aa-717a-11e7-9b41-5466ffb1e02c.png">

**Comment by nyedidikeke** [comment]
It's been fixed; this thread can be marked closed.

**Comment by laudarch** [comment]
Fixed.
